<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Content\Projectiles\MobileForge.png" />
	  <None Remove="Content\Projectiles\MobileSafe.png" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="CalamityMod">
	    <HintPath>..\ModAssemblies\CalamityMod_v2.2.1.dll</HintPath>
	  </Reference>
	  <Reference Include="InfernumMode">
	    <HintPath>..\ModAssemblies\InfernumMode_v2.0.1.34.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<!-- References -->

</Project>